sonar.projectKey=samukaoliveira_lingSam_AZ9hFhzjDty5ce5JF9Jw

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=
