spring.application.name=lingSam

# ===========================
# SERVIDOR
# ===========================

server.port=8080

# ===========================
# DATASOURCE
# ===========================

spring.datasource.url=jdbc:h2:file:./database/lingstudy
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#spring.datasource.url=jdbc:postgresql://localhost:5432/lingstudy
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

#################################################
# H2 Console
#################################################

spring.h2.console.enabled=true
spring.h2.console.path=/h2

# ===========================
# JPA
# ===========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# THYMELEAF
# ===========================

spring.thymeleaf.cache=false

# ===========================
# LOG
# ===========================

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===========================
# USUÁRIO PADRÃO
# ===========================

app.user.username=admin
app.user.password=admin123
app.user.name=Administrador